export const dashboardData = {
  overview: {
    totalProjects: 45,
    valueGenerated: 12500000,
    actualPercentage: 87,
    pdoEngagements: 23,
    externalEngagements: 15,
    valueContributions: [
      { project: "Digital Transformation Initiative", contribution: 35 },
      { project: "RPA Implementation", contribution: 28 },
      { project: "Data Analytics Platform", contribution: 22 },
      { project: "Cloud Migration", contribution: 15 },
    ],
  },
  digitalAmbition: [
    {
      programName: "Digital Transformation Initiative",
      phase: "Phase 3",
      comments: "Implementation of core modules completed, user training in progress",
      status: "On Track" as const,
    },
    {
      programName: "RPA Implementation",
      phase: "Phase 2",
      comments: "Bot development completed for 5 processes, testing phase ongoing",
      status: "Delayed by 20%" as const,
    },
    {
      programName: "Data Analytics Platform",
      phase: "Phase 1",
      comments: "Infrastructure setup completed, data integration challenges identified",
      status: "On Track" as const,
    },
    {
      programName: "Cloud Migration",
      phase: "Phase 2",
      comments: "Security compliance review taking longer than expected",
      status: "Delayed by >50%" as const,
    },
    {
      programName: "AI/ML Center of Excellence",
      phase: "Phase 1",
      comments: "Resource allocation pending, budget approval required",
      status: "Significantly Delayed" as const,
    },
  ],
  rpa: {
    kpis: {
      liveProcesses: 12,
      inDevelopment: 8,
      planned: 15,
      valueGenerated: 3200000,
      manhourSavings: 45,
      robots: 18,
    },
    savingsByDirectorate: [
      { name: "Operations", value: 1200 },
      { name: "Finance", value: 800 },
      { name: "HR", value: 600 },
      { name: "IT", value: 400 },
      { name: "Procurement", value: 200 },
    ],
    projectStatusByDirectorate: [
      {
        directorate: "Operations",
        planning: 3,
        development: 2,
        production: 5,
        underDiscussion: 1,
      },
      {
        directorate: "Finance",
        planning: 2,
        development: 3,
        production: 3,
        underDiscussion: 2,
      },
      {
        directorate: "HR",
        planning: 4,
        development: 1,
        production: 2,
        underDiscussion: 1,
      },
      {
        directorate: "IT",
        planning: 1,
        development: 2,
        production: 2,
        underDiscussion: 0,
      },
    ],
  },
  ideHighlights: [
    {
      title: "Innovation Lab Launch",
      description: "Successfully launched the PDO Innovation Lab with state-of-the-art facilities",
      details: [
        "Equipped with latest development tools and hardware",
        "Collaborative workspace for cross-functional teams",
        "Integration with external innovation partners",
        "Monthly innovation challenges and hackathons",
      ],
    },
    {
      title: "Digital Skills Academy",
      description: "Comprehensive digital skills training program for all employees",
      details: [
        "Over 500 employees trained in digital literacy",
        "Specialized tracks for different roles and departments",
        "Certification programs with industry partners",
        "Continuous learning platform with 24/7 access",
      ],
    },
    {
      title: "Startup Collaboration Program",
      description: "Partnership with local and international startups for innovation",
      details: [
        "10 active partnerships with technology startups",
        "Pilot programs for emerging technologies",
        "Mentorship and funding opportunities",
        "Regular startup pitch sessions and demo days",
      ],
    },
    {
      title: "Digital Innovation Awards",
      description: "Recognition program for outstanding digital innovation contributions",
      details: [
        "Quarterly awards for innovative solutions",
        "Categories for individual and team contributions",
        "Monetary rewards and career advancement opportunities",
        "Showcase of winning solutions across the organization",
      ],
    },
  ],
  capabilityDevelopment: [
    {
      title: "Training Programs",
      totalCount: 24,
      activities: [
        "Digital Leadership Bootcamp",
        "Data Science Fundamentals",
        "Agile Project Management",
        "Cybersecurity Awareness",
      ],
      icon: "GraduationCap",
    },
    {
      title: "Workshops",
      totalCount: 18,
      activities: [
        "Design Thinking Sessions",
        "Innovation Methodology",
        "Digital Transformation Best Practices",
        "Technology Trend Analysis",
      ],
      icon: "Users",
    },
    {
      title: "Certifications",
      totalCount: 156,
      activities: [
        "Cloud Architecture Certification",
        "Project Management Professional",
        "Data Analytics Certification",
        "Digital Marketing Certification",
      ],
      icon: "Award",
    },
    {
      title: "Knowledge Sharing",
      totalCount: 32,
      activities: [
        "Monthly Tech Talks",
        "Best Practices Documentation",
        "Cross-Department Collaboration",
        "External Conference Participation",
      ],
      icon: "BookOpen",
    },
  ],
  recognitionAwards: [
    {
      name: "Ahmed Al-Rashid",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Outstanding contribution to RPA implementation, saving 15K manhours annually",
      type: "individual" as const,
    },
    {
      name: "Digital Innovation Team",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Excellence in Digital Transformation - Q3 2024 Team Achievement Award",
      type: "team" as const,
      teamMembers: ["Sarah Al-Zahra", "Mohammed Al-Kindi", "Fatima Al-Balushi", "Omar Al-Hinai"],
    },
    {
      name: "Layla Al-Mamari",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Innovation Champion - Leading AI/ML initiatives and knowledge transfer",
      type: "individual" as const,
    },
    {
      name: "Data Analytics Squad",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Best Data-Driven Solution - Predictive Maintenance Dashboard",
      type: "team" as const,
      teamMembers: ["Khalid Al-Busaidi", "Amina Al-Rawahi", "Saif Al-Ghafri"],
    },
    {
      name: "Yusuf Al-Harthi",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Digital Leadership Excellence - Driving cultural transformation",
      type: "individual" as const,
    },
    {
      name: "Cloud Migration Team",
      photo: "/placeholder.svg?height=64&width=64",
      recognition: "Technical Excellence Award - Successful cloud infrastructure migration",
      type: "team" as const,
      teamMembers: ["Nasser Al-Siyabi", "Maryam Al-Kharusi", "Abdullah Al-Farsi", "Huda Al-Shihi", "Tariq Al-Balushi"],
    },
  ],
  teamBuilding: [
    {
      teamName: "Digital Innovation Team",
      date: "2024-01-15",
      activityName: "Innovation Workshop & Team Retreat",
      status: "Done" as const,
    },
    {
      teamName: "RPA Development Squad",
      date: "2024-01-22",
      activityName: "Technical Skills Workshop",
      status: "Done" as const,
    },
    {
      teamName: "Data Analytics Team",
      date: "2024-02-05",
      activityName: "Department Breakfast & Planning Session",
      status: "Done" as const,
    },
    {
      teamName: "Cloud Infrastructure Team",
      date: "2024-02-14",
      activityName: "Valentine's Day Team Lunch",
      status: "Done" as const,
    },
    {
      teamName: "AI/ML Research Group",
      date: "2024-02-28",
      activityName: "Wellness Event - Hiking Trip",
      status: "Done" as const,
    },
    {
      teamName: "Digital Transformation Office",
      date: "2024-03-10",
      activityName: "Quarterly Team Building Event",
      status: "In Progress" as const,
    },
    {
      teamName: "Cybersecurity Team",
      date: "2024-03-18",
      activityName: "Security Awareness Workshop",
      status: "In Progress" as const,
    },
    {
      teamName: "UX/UI Design Team",
      date: "2024-03-25",
      activityName: "Creative Workshop & Team Bonding",
      status: "In Progress" as const,
    },
  ],
}
